import React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Link, scroller } from 'react-scroll'
//import Image from 'next/image'

import IntroComponent from '@/components/IntroComponent/IntroComponent'
import OutstandingComponent from '@/components/OutstandingComponent/OutstandingComponent'
import FormComponent from '@/components/FormComponent/FormComponent'

const inter = Inter({ subsets: ['latin'] })




export default function Home() {

  const [scrollPosition, setScrollPosition] = React.useState(0);
  React.useEffect(() => {
    const handleScroll = () => {
      const currentPosition = window.scrollY;
      setScrollPosition(currentPosition);
    };

    window.addEventListener('scroll', handleScroll);
    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Softfin Landing Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={`${styles.nav} ${inter.className} ${scrollPosition >= 70 ? styles.navBackground : ''}`}>
        <h1 className={`${styles.navBrand} `}>Softfin</h1>
        {/* <Image
          src="/logo.png"
          width={200}
          height={58}
          
          alt="Picture of the author"
        /> */}
        <div className={`${styles.navLinks}`}>
          <Link to='intro' smooth={true} duration={700} offset={-70} >Home</Link>
          <Link to='info' smooth={true} duration={700} offset={-70} >About</Link>
          <Link to='categories' smooth={true} duration={700} offset={-70} >Store</Link>
          <Link to='gallery' smooth={true} duration={700} offset={-70} >Gallery</Link>
          <Link to='form' smooth={true} duration={700} offset={-70} >Contact</Link>
         {/*  <a href='#'>Control panel</a> */}
         
        </div>
      </nav>
   
      <main className={`${styles.main} ${inter.className}`}>
        <section id='intro' className={`${styles.intro} ${inter.className}`}>
          <IntroComponent 
           handleFormSection={(link) => {
            scroller.scrollTo(`${link}`, {
              duration: 900,
              delay: 0,
              smooth: "easeInOutQuart",
              offset: -70
            });
           }}
          />
        </section>
        <section id='outstanding' className={`${styles.section} ${inter.className}`}>
          
          
           <OutstandingComponent />
        </section>
        <section id='description' className={`${styles.section} ${inter.className}`}>
          Description Content
        </section>
        <section id='info' className={`${styles.introContent} ${styles.section} ${inter.className}`}>
          General Info Content
        </section>
        <section id='categories' className={`${styles.section} ${inter.className}`}>
          Product Categories Content
        </section>
        <section id='gallery' className={`${styles.section} ${inter.className}`}>
          Gallery Content
        </section>
        <section id='form' name='form' className={`${styles.section} ${inter.className}`}>
          <FormComponent />
        </section>
        <footer className={`${styles.section} ${inter.className}`}>
          Footer
          <br/>
          
          Image by <a href="https://www.freepik.com/free-photo/variety-dark-shapes-background_9464829.htm#query=background&position=8&from_view=search&track=robertav1_2_sidr">Freepik</a>
          Image by <a href="https://www.freepik.com/free-photo/wavy-copy-space-background-close-up_9465188.htm#query=background&position=22&from_view=search&track=robertav1_2_sidr">Freepik</a>
          Image by <a href="https://www.freepik.com/free-photo/layers-black-torn-paper_11068923.htm#page=2&query=background&position=30&from_view=search&track=robertav1_2_sidr">Freepik</a>
        </footer>
      </main>
    </>
  )
}
